[test]
timeout = 60000
coverage = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
  "tests/*.ts",
  "tests/**/*.ts",
  "**/*.spec.ts",
  "**/*.test.ts",
  "dist/**",
  "build/**",
]
