name: Publish Package to npmjs
on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  package-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - name: Install dependencies
        run: bun install

      - name: Run E2E
        run: bun e2e

  release:
    runs-on: ubuntu-latest
    needs: package-test
    environment:
      name: npm
      url: https://www.npmjs.com/package/factsets
    permissions:
      discussions: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions/setup-node@v6
        with:
          node-version: '25'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run dist

      - run: npm publish --provenance --access public

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          discussion_category_name: Announcements
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: |-
            README.md
            LICENSE
